function Rover= roverinit(RRTState)
    Rover.PointA = RRTState.PointA;
    Rover.PointB = RRTState.PointB;
    Rover.Length = 0.2488;
    Rover.Width = 0.35;
    Rover.Radius = 0.5*norm([Rover.Length Rover.Width]);
    Rover.Dimensions = RRTState.Dimensions;
    Rover.Obstacles = RRTState.Obstacles;
    Rover.Kpu = 15;
    Rover.Kiu = 30;
    Rover.kdh = 0.05;
    Rover.Kph = 20;
    Rover.Kih = 0.1;
    Rover.kdu = 0.01;
    Rover.dt = 0.02;
    Rover.e_u_1 = [0 0];
    Rover.u_sur_1 =[0 0];
    Rover.waypoints = RRTState.finalpathvertices(:,1:2);
    Rover.pos_curr = Rover.waypoints(1,1:2);
    Rover.Travel = [Rover.pos_curr];
    Rover.counter = 0;
end