function Rover= roverinit(RRTState)
Rover.PointA = RRTState.PointA;
Rover.PointB = RRTState.PointB;
Rover.Length = 0.35;
Rover.Width = 0.2488;
Rover.n=1;
% Rover.LoSRadius = Rover.n*Rover.Length;
Rover.Radius = 0.5*norm([Rover.Length Rover.Width]);
Rover.LoSRadius = Rover.n*(Rover.Length+Rover.Radius);
Rover.Dimensions = RRTState.Dimensions;
Rover.Obstacles = RRTState.Obstacles;
Rover.Kpu = 15;
Rover.Kiu = 30;
Rover.kdh = 0.05;
Rover.Kph = 20;
Rover.Kih = 0.1;
Rover.kdu = 0.01;
Rover.dt = 0.001;
% Rover.dt = 0.01;

Rover.e_u_1 = [0 0];
Rover.u_sur_1 =[0 0];
Rover.waypoints = RRTState.finalpathvertices(:,1:2);
% Rover.pos_curr = Rover.waypoints(1,1:2);
Rover.pos_curr = Rover.waypoints(1,1:2);
Rover.pos_des =[0 0];
Rover.prev_wayPoint = Rover.waypoints(1,1:2);
Rover.Travel = [Rover.pos_curr];
Rover.counter = 0;
Rover.RadiusAcc = 0.4;
Rover.theta = 10;
Rover.theta_rad = Rover.theta*pi/180;
Rover.wpacc_ind = 0;
Rover.obst =[];
end